version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
